name: Bug Report
description: Report a bug or unexpected behavior
title: "[Bug] "
labels: ["bug"]
body:
  - type: dropdown
    id: platform
    attributes:
      label: OS / Platform
      options:
        - macOS (Apple Silicon)
        - macOS (Intel)
        - Windows
        - Linux (deb)
        - Linux (AppImage)
    validations:
      required: true

  - type: input
    id: version
    attributes:
      label: App Version
      placeholder: "e.g., v0.2.0"
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: Description
      description: What happened?
      placeholder: Describe the bug clearly
    validations:
      required: true

  - type: textarea
    id: steps
    attributes:
      label: Steps to Reproduce
      placeholder: |
        1. Open the app
        2. Click on '...'
        3. See error
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      placeholder: What did you expect to happen?
    validations:
      required: true

  - type: textarea
    id: logs
    attributes:
      label: Log Output (optional)
      description: |
        Paste any relevant log output. The log file is at:
        - macOS: `~/Library/Application Support/com.kody.snap-data-explorer-app/snap_explorer.log`
        - Windows: `%APPDATA%/com.kody.snap-data-explorer-app/snap_explorer.log`
        - Linux: `~/.local/share/com.kody.snap-data-explorer-app/snap_explorer.log`
      render: text
    validations:
      required: false
